/**
 * Data access layer for Next.js pages.
 *
 * All data is pre-generated by `scripts/generate-page-data.mjs` into
 * `page-data/`. Pages read only their own small JSON file instead of
 * processing the full web-bundle.json at render time.
 */

import { promises as fs } from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type DomainSummary = {
  slug: string;
  title: string;
  sources: number;
  entities: number;
  claims: number;
  topicCount: number;
  topConcepts: Array<{ label: string; count: number }>;
  overviewPapers: number;
  topicalPapers: number;
  facetCounts: Record<string, number>;
  hasDetail: boolean;
  abstractionLabel?: string;
};

export type DomainDetail = DomainSummary & {
  subgenres: Array<{
    subgenre_id: string;
    label: string;
    parent_id: string | null;
    level: number;
    member_terms: string[];
    paper_ids: string[];
    top_entities: string[];
    top_properties: string[];
    summary: string;
  }>;
  roleProfiles: Array<{
    label: string;
    semantic_role: string;
    topic_role: string;
    ui_role: string;
    confidence: number;
    evidence_count: number;
  }>;
  risingTopics?: Array<{
    id: string;
    label: string;
    trend: string;
    year_total?: number;
  }>;
  hierarchy?: {
    root_topics?: number;
    descendant_topics?: number;
    max_depth?: number;
    leaf_topics?: number;
  };
};

export type TopicPaper = {
  source_id: string;
  title: string;
  year: number | null;
  url: string;
  doi: string | null;
  short_summary: string;
  cited_by_count: number;
  adjusted_cited_by_count: number;
  concepts: string[];
  assignment: {
    confidence: number;
    score: number;
    matched_terms: string[];
    secondary_subgenre_ids: string[];
  } | null;
};

export type TopicDetail = {
  domain: DomainSummary;
  topic: {
    subgenre_id: string;
    label: string;
    summary: string;
    paper_ids: string[];
    parent_id: string | null;
    level: number;
    member_terms: string[];
    top_entities: string[];
    top_properties: string[];
  };
  children: Array<{ subgenre_id: string; label: string; paperCount: number }>;
  /** Pre-computed ancestor breadcrumb (excludes current topic). */
  ancestorTrail: Array<{ href: string; label: string }>;
  /** Pre-computed grandchildren keyed by child subgenre_id. */
  grandchildren: Record<string, Array<{ subgenre_id: string; label: string }>>;
  /** Sibling topics sharing the same parent. */
  siblingTopics: Array<{ subgenre_id: string; label: string; paperCount: number }>;
  papers: TopicPaper[];
};

export type PaperDetail = {
  domain: DomainSummary;
  paper: TopicPaper & {
    authors: string[];
    claims: Array<{
      property_name: string;
      value_text: string;
      unit: string;
      evidence_text: string;
      confidence: number;
      polarity: string;
      qualifiers: string[];
    }>;
    entities: Array<{
      canonical_id: string;
      canonical_name: string;
      entity_type: string;
      evidence_count: number;
    }>;
    primaryTopicId: string | null;
    primaryTopicLabel: string | null;
    secondaryTopicIds: string[];
    secondaryTopicLabels: string[];
    relatedPapers: Array<{
      source_id: string;
      title: string;
      year: number | null;
      cited_by_count: number;
      score: number;
    }>;
  };
};

export type TopicAtlasItem = {
  subgenre_id: string;
  label: string;
  summary: string;
  paperCount: number;
  subtopicCount: number;
  tags: string[];
  trendScore: number;
  trendLabel: "rising" | "steady";
  children: Array<{
    subgenre_id: string;
    label: string;
    paperCount: number;
  }>;
  featuredPapers: TopicPaper[];
};

export type DomainTopicsIndex = {
  domain: DomainSummary;
  hierarchy: {
    maxDepth: number;
    rootTopics: number;
    descendantTopics: number;
    leafTopics: number;
  };
  topics: TopicAtlasItem[];
};

export type DomainPapersIndex = {
  domain: DomainSummary;
  shelves: Array<{
    topicId: string;
    topicLabel: string;
    papers: TopicPaper[];
  }>;
  archive: Array<TopicPaper & { primaryTopicId: string | null; primaryTopicLabel: string | null }>;
  relatedDomains: Array<{ slug: string; title: string }>;
};

export type PortalCategory = {
  label: string;
  slug: string;
  description: string;
  count: number;
  domains: Array<{ slug: string; title: string; sources?: number; topicCount?: number }>;
};

export type PortalData = {
  updated_at?: string;
  total_domains?: number;
  categories?: PortalCategory[];
  domains?: Array<{
    slug: string;
    title: string;
    sources?: number;
    entities?: number;
    claims?: number;
    parent_subgenres?: number;
    overview_partition_summary?: {
      overview_papers?: number;
      topical_papers?: number;
      facet_counts?: Record<string, number>;
    };
    abstraction_label?: string;
  }>;
};

// ---------------------------------------------------------------------------
// Internal
// ---------------------------------------------------------------------------

const PAGE_DATA_ROOT = path.join(process.cwd(), "page-data");

const _cache = new Map<string, unknown>();

async function readPageData<T>(filePath: string): Promise<T | null> {
  if (_cache.has(filePath)) {
    return _cache.get(filePath) as T;
  }
  try {
    const raw = await fs.readFile(filePath, "utf8");
    const parsed = JSON.parse(raw) as T;
    _cache.set(filePath, parsed);
    return parsed;
  } catch {
    _cache.set(filePath, null);
    return null;
  }
}

// ---------------------------------------------------------------------------
// Static params enumeration (uses directory listing — no JSON parsing)
// ---------------------------------------------------------------------------

export async function listDomainSlugs(): Promise<string[]> {
  try {
    const entries = await fs.readdir(PAGE_DATA_ROOT, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort((a, b) => a.localeCompare(b));
  } catch {
    return [];
  }
}

export async function listTopicStaticParams(): Promise<
  Array<{ slug: string; topicId: string }>
> {
  const slugs = await listDomainSlugs();
  const out: Array<{ slug: string; topicId: string }> = [];
  await Promise.all(
    slugs.map(async (slug) => {
      try {
        const files = await fs.readdir(path.join(PAGE_DATA_ROOT, slug, "topics"));
        for (const file of files) {
          if (file.endsWith(".json")) {
            out.push({ slug, topicId: file.slice(0, -5) });
          }
        }
      } catch {
        // skip domains without topics dir
      }
    })
  );
  return out;
}

export async function listPaperStaticParams(): Promise<
  Array<{ slug: string; paperId: string }>
> {
  const slugs = await listDomainSlugs();
  const out: Array<{ slug: string; paperId: string }> = [];
  await Promise.all(
    slugs.map(async (slug) => {
      try {
        const files = await fs.readdir(path.join(PAGE_DATA_ROOT, slug, "papers"));
        for (const file of files) {
          if (file.endsWith(".json")) {
            out.push({ slug, paperId: file.slice(0, -5) });
          }
        }
      } catch {
        // skip domains without papers dir
      }
    })
  );
  return out;
}

// ---------------------------------------------------------------------------
// Page data readers
// ---------------------------------------------------------------------------

export async function getPortalData(): Promise<PortalData | null> {
  return readPageData<PortalData>(path.join(PAGE_DATA_ROOT, "portal.json"));
}

export async function listPortalCategories(): Promise<PortalCategory[]> {
  const portal = await getPortalData();
  return portal?.categories ?? [];
}

export async function getCategoryBySlug(categorySlug: string): Promise<PortalCategory | null> {
  const portal = await getPortalData();
  const cat = portal?.categories?.find((c) => c.slug === categorySlug);
  if (!cat) return null;
  const domainMap = new Map((portal?.domains ?? []).map((d) => [d.slug, d]));
  return {
    ...cat,
    domains: cat.domains.map((d) => ({
      ...d,
      sources: domainMap.get(d.slug)?.sources,
      topicCount: domainMap.get(d.slug)?.parent_subgenres,
    })),
  };
}

export async function listCategorySlugs(): Promise<string[]> {
  const cats = await listPortalCategories();
  return cats.map((c) => c.slug).filter(Boolean).sort((a, b) => a.localeCompare(b));
}

export async function listDomains(): Promise<DomainSummary[]> {
  const portal = await getPortalData();
  const slugs = portal?.domains?.map((d) => d.slug).filter(Boolean) ?? await listDomainSlugs();
  const summaries = await Promise.all(
    slugs.map((slug) =>
      readPageData<DomainSummary>(path.join(PAGE_DATA_ROOT, slug, "summary.json"))
    )
  );
  return (summaries.filter(Boolean) as DomainSummary[]).sort(
    (a, b) => b.sources - a.sources || a.title.localeCompare(b.title)
  );
}

export async function getDomainDetail(slug: string): Promise<DomainDetail | null> {
  return readPageData<DomainDetail>(path.join(PAGE_DATA_ROOT, slug, "domain.json"));
}

export async function getDomainTopicsIndex(slug: string): Promise<DomainTopicsIndex | null> {
  return readPageData<DomainTopicsIndex>(
    path.join(PAGE_DATA_ROOT, slug, "topics-index.json")
  );
}

export async function getDomainPapersIndex(slug: string): Promise<DomainPapersIndex | null> {
  return readPageData<DomainPapersIndex>(
    path.join(PAGE_DATA_ROOT, slug, "papers-index.json")
  );
}

export async function getTopicDetail(
  slug: string,
  topicId: string
): Promise<TopicDetail | null> {
  return readPageData<TopicDetail>(
    path.join(PAGE_DATA_ROOT, slug, "topics", `${topicId}.json`)
  );
}

export async function getPaperDetail(
  slug: string,
  paperId: string
): Promise<PaperDetail | null> {
  return readPageData<PaperDetail>(
    path.join(PAGE_DATA_ROOT, slug, "papers", `${paperId}.json`)
  );
}
